version: '2.1'

services:
  app:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1.102
    command: dotnet run -p src/<project_name>
    ports:
      - "5003:5003"
    healthcheck:
      test: echo | telnet 0.0.0.0 5003
      timeout: 10s
      retries: 10
    volumes:
      - ./src:/src
    networks:
      default:
